# Generated by Django 5.2.16 on 2026-07-23 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage1_passed', models.BooleanField()),
                ('hemoglobin_g_dl', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('TEMP_DEFERRED', 'Temporarily deferred'), ('INELIGIBLE', 'Ineligible')], max_length=15)),
                ('failed_reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='donors.donor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
