# Generated by Django 5.2.16 on 2026-07-23 23:33

import django.core.validators
import donors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_screeningrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='id_document',
            field=models.FileField(help_text='JPG, PNG or PDF. Visible only to administrators reviewing your registration.', upload_to='donor_ids/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'], message='Upload a JPG, PNG or PDF copy of your ID.'), donors.validators.validate_id_size]),
        ),
    ]
