# Generated by Django 5.2.14 on 2026-09-10 14:30

import cbods.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='contact_phone',
            field=models.CharField(max_length=20, validators=[cbods.validators.validate_phone_number]),
        ),
    ]
