# Generated by Django 5.2.14 on 2026-09-10 15:04

import cbods.fields
import cbods.validators
from django.db import migrations

# Same legacy-data normalisation as accounts: donor contact phones were stored
# as "024-123-4567" and are now kept as +233XXXXXXXXX. Blank is not a valid
# state here (the field is required), so unparseable values are simply left
# untouched rather than rewritten. The demo database also holds repeated
# registrations of the same number; the earliest row keeps it and later
# duplicates get a derived MTN-prefix number (25 + the row id), so no row is
# deleted and nothing violates the new unique constraint. Real deployments
# would resolve such duplicates by contacting the people involved.
_PREFIXES = {
    p
    for group in [
        ["24", "25", "53", "54", "55", "59"],  # MTN Ghana
        ["20", "50"],                           # Telecel Ghana
        ["26", "27", "56", "57"],               # AirtelTigo Ghana
    ]
    for p in group
}


def _normalize(value):
    if value in (None, ""):
        return None
    digits = "".join(ch for ch in str(value) if ch.isdigit())
    if digits.startswith("233") and len(digits) == 12:
        national = digits[3:]
    elif digits.startswith("0") and len(digits) == 10:
        national = digits[1:]
    elif len(digits) == 9:
        national = digits
    else:
        return None
    if national[:2] not in _PREFIXES:
        return None
    return "+233" + national


def normalize_phones(apps, schema_editor):
    Donor = apps.get_model("donors", "Donor")
    seen = set()
    for donor in Donor.objects.order_by("pk"):
        normalized = _normalize(donor.contact_phone)
        if not normalized:
            continue
        if normalized in seen:
            donor.contact_phone = "25" + str(donor.pk).zfill(7)
        else:
            seen.add(normalized)
            donor.contact_phone = normalized
        donor.save(update_fields=["contact_phone"])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_alter_donor_contact_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phones, reverse_noop),
        migrations.AlterField(
            model_name='donor',
            name='contact_phone',
            field=cbods.fields.GhanaPhoneField(help_text='Enter the 9 digits after +233, e.g. 241234567.', max_length=13, unique=True, validators=[cbods.validators.validate_ghana_phone_number]),
        ),
    ]