# Generated by Django 5.2.14 on 2026-08-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DONOR', 'Donor'), ('PATIENT', 'Patient'), ('HOSPITAL_STAFF', 'Hospital Staff'), ('HOSPITAL', 'Hospital')], default='DONOR', max_length=20),
        ),
    ]
