# Generated by Django 5.2.14 on 2026-09-10 15:04

import cbods.fields
import cbods.validators
from django.db import migrations

# Phone numbers used to be stored in the 10-digit leading-zero form
# ("024-123-4567") or already 9-digit; the app now stores the canonical
# +233XXXXXXXXX form and enforces it with a unique constraint. Existing rows
# are normalised here (the parseable ones), and blank values become NULL so
# the unique constraint treats "no phone" as absent rather than as a value
# every account-less user would collide on. Unparseable values are left
# untouched: they cannot crash the migration, and any later edit goes through
# validation again.
_PREFIXES = {
    p
    for group in [
        ["24", "25", "53", "54", "55", "59"],  # MTN Ghana
        ["20", "50"],                           # Telecel Ghana
        ["26", "27", "56", "57"],               # AirtelTigo Ghana
    ]
    for p in group
}


def _normalize(value):
    if value in (None, ""):
        return None
    digits = "".join(ch for ch in str(value) if ch.isdigit())
    if digits.startswith("233") and len(digits) == 12:
        national = digits[3:]
    elif digits.startswith("0") and len(digits) == 10:
        national = digits[1:]
    elif len(digits) == 9:
        national = digits
    else:
        return None
    if national[:2] not in _PREFIXES:
        return None
    return "+233" + national


def normalize_phones(apps, schema_editor):
    """Normalise to +233XXXXXXXXX, blank -> NULL, and de-duplicate.

    The demo database accumulated rows sharing one number (repeated manual
    sign-ups). Phone is optional on the account, so the earliest row keeps the
    number and later duplicates become NULL — honest "no phone on file"
    rather than a guessed number.
    """
    User = apps.get_model("accounts", "User")
    seen = set()
    for user in User.objects.order_by("pk"):
        if user.phone == "":
            user.phone = None
            user.save(update_fields=["phone"])
            continue
        normalized = _normalize(user.phone)
        if not normalized:
            continue
        if normalized in seen:
            user.phone = None
        else:
            seen.add(normalized)
            user.phone = normalized
        user.save(update_fields=["phone"])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_phone'),
    ]

    operations = [
        # The column becomes nullable first, so blank values can be stored as
        # NULL before the unique constraint lands ("" duplicates would break
        # the table rebuild that adds it).
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=cbods.fields.GhanaPhoneField(blank=True, help_text='Enter the 9 digits after +233, e.g. 241234567.', max_length=13, null=True, validators=[cbods.validators.validate_ghana_phone_number]),
        ),
        migrations.RunPython(normalize_phones, reverse_noop),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=cbods.fields.GhanaPhoneField(blank=True, help_text='Enter the 9 digits after +233, e.g. 241234567.', max_length=13, null=True, unique=True, validators=[cbods.validators.validate_ghana_phone_number]),
        ),
    ]