# Generated by Django 5.2.17 on 2026-09-13 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_bloodbag_reserved_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbag',
            name='status',
            field=models.CharField(choices=[('UNTESTED', 'Untested'), ('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('ISSUED', 'Issued'), ('EXPIRED', 'Expired'), ('DISCARDED', 'Discarded')], default='UNTESTED', max_length=20),
        ),
        migrations.CreateModel(
            name='TTITestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiv', models.CharField(blank=True, choices=[('NEGATIVE', 'Non-reactive (negative)'), ('POSITIVE', 'Reactive (positive)')], max_length=8, null=True)),
                ('hepatitis_b', models.CharField(blank=True, choices=[('NEGATIVE', 'Non-reactive (negative)'), ('POSITIVE', 'Reactive (positive)')], max_length=8, null=True)),
                ('hepatitis_c', models.CharField(blank=True, choices=[('NEGATIVE', 'Non-reactive (negative)'), ('POSITIVE', 'Reactive (positive)')], max_length=8, null=True)),
                ('syphilis', models.CharField(blank=True, choices=[('NEGATIVE', 'Non-reactive (negative)'), ('POSITIVE', 'Reactive (positive)')], max_length=8, null=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('discarded_reason', models.TextField(blank=True, help_text='Reactive marker(s), when the unit was discarded.')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tti_record', to='inventory.donation')),
                ('tested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TTI test record',
            },
        ),
    ]
