# Generated by Django 5.2.14 on 2026-09-10 15:04

import cbods.fields
import cbods.validators
from django.db import migrations

# Same legacy-data normalisation as accounts: hospital phones were stored as
# "030-222-1111" (landline-style) and are now kept as +233XXXXXXXXX. Only
# numbers that normalise to a recognised mobile prefix are rewritten; anything
# else stays as stored and will surface in form validation if edited.
_PREFIXES = {
    p
    for group in [
        ["24", "25", "53", "54", "55", "59"],  # MTN Ghana
        ["20", "50"],                           # Telecel Ghana
        ["26", "27", "56", "57"],               # AirtelTigo Ghana
    ]
    for p in group
}


def _normalize(value):
    if value in (None, ""):
        return None
    digits = "".join(ch for ch in str(value) if ch.isdigit())
    if digits.startswith("233") and len(digits) == 12:
        national = digits[3:]
    elif digits.startswith("0") and len(digits) == 10:
        national = digits[1:]
    elif len(digits) == 9:
        national = digits
    else:
        return None
    if national[:2] not in _PREFIXES:
        return None
    return "+233" + national


def normalize_phones(apps, schema_editor):
    Hospital = apps.get_model("hospitals", "Hospital")
    for hospital in Hospital.objects.all():
        normalized = _normalize(hospital.phone)
        if normalized:
            hospital.phone = normalized
            hospital.save(update_fields=["phone"])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_alter_hospital_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phones, reverse_noop),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=cbods.fields.GhanaPhoneField(help_text='Enter the 9 digits after +233, e.g. 241234567.', max_length=13, unique=True, validators=[cbods.validators.validate_ghana_phone_number]),
        ),
    ]