"""
Django settings for cbods project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment; the fallback is a throwaway development key.
# Set DJANGO_SECRET_KEY to a fresh random value anywhere this is reachable by
# other people — the fallback below is public in the repository history.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-do-not-use-outside-local-development",
)

# Off unless DJANGO_DEBUG is explicitly truthy, so a deployed copy cannot leak
# tracebacks just because someone forgot to change a setting.
DEBUG = os.environ.get("DJANGO_DEBUG", "1").lower() in ("1", "true", "yes")

# Local dev plus any hosts named in DJANGO_ALLOWED_HOSTS (comma-separated),
# e.g. the LAN IP used for a partner demo.
ALLOWED_HOSTS = ["localhost", "127.0.0.1"] + [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'hospitals',
    'donors',
    'inventory',
    'requests_app',
    'organs',
    'notifications',
    'audit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cbods.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.unread_count',
                'cbods.context_processors.ghana_phone',
            ],
        },
    },
]

WSGI_APPLICATION = 'cbods.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Local time for everyone who reads a screen: hospital staff reconcile these
# timestamps against paper records and wall clocks. Storage stays UTC.
TIME_ZONE = 'Africa/Accra'

USE_I18N = True

USE_TZ = True

# One date format everywhere, so a raw {{ bag.expiry_date }} and an explicit
# {{ x|date:"Y-m-d" }} cannot disagree on the same page. This has to go through
# FORMAT_MODULE_PATH rather than a plain DATE_FORMAT setting: localisation is
# always on since Django 5.0, and the locale's own format module takes
# precedence over the setting.
FORMAT_MODULE_PATH = 'cbods.formats'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Idle session timeout: 15 minutes without a request logs the user out.
# SESSION_SAVE_EVERY_REQUEST rolls the deadline forward on every request
# (cookie max-age and the DB expire_date both refresh), so this is a true
# idle timeout rather than a fixed one counted from login.
SESSION_COOKIE_AGE = 15 * 60
SESSION_SAVE_EVERY_REQUEST = True

#
# Email delivery
# --------------
# Default (no env vars): the console backend — emails print to the server log,
# nothing is delivered. The subclass additionally logs any password reset link
# behind a fixed marker, so it can be found by searching a busy log instead of
# read out of it.
#
# Real SMTP: set EMAIL_HOST to switch to a genuine SMTP backend for every
# message the app sends (notifications and password resets). Credentials are
# only read when EMAIL_HOST_USER is set, so an unauthenticated debug sink needs
# just one variable:
#
#   set EMAIL_HOST=localhost          (then, in another terminal:)
#   python manage.py smtp_debugserver
#
# Recommended relay — Brevo (free tier: 300 emails/day, forever, no credit
# card; no 2-Step Verification, no per-user app passwords, no domain needed).
# Sign up at brevo.com, then Settings > SMTP & API: the SMTP login and an SMTP
# key are both shown there (use an SMTP key, not an API key). Verify a sender
# address once — your signup email works — and send from that:
#
#   set EMAIL_HOST=smtp-relay.brevo.com
#   set EMAIL_PORT=587
#   set EMAIL_HOST_USER=your-smtp-login@smtp-brevo.com
#   set EMAIL_HOST_PASSWORD=xsmtpsib-xxxxxxxxxxxxxxxxxxxxxxxx
#   set EMAIL_USE_TLS=1
#   set DEFAULT_FROM_EMAIL=you@example.com   (optional — defaults to the login)
#
# Gmail works too, but needs 2-Step Verification plus a 16-char app password
# (https://myaccount.google.com/apppasswords), not the account password:
#
#   set EMAIL_HOST=smtp.gmail.com
#   set EMAIL_PORT=587
#   set EMAIL_HOST_USER=you@gmail.com
#   set EMAIL_HOST_PASSWORD=xxxxxxxxxxxxxxxx
#   set EMAIL_USE_TLS=1
#   set DEFAULT_FROM_EMAIL=you@gmail.com
#
# RetryingSMTPBackend wraps Django's SMTP backend with one retry of the
# connection step, for networks that intermittently stall the initial connect
# (see accounts/email.py).
SMTP_BACKEND = 'accounts.email.RetryingSMTPBackend'
_console_backend = 'accounts.email.LoggingConsoleEmailBackend'
_email_host = os.environ.get('EMAIL_HOST', '').strip()
EMAIL_BACKEND = SMTP_BACKEND if _email_host else _console_backend
EMAIL_HOST = _email_host
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', '0').lower() in ('1', 'true', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', '0').lower() in ('1', 'true', 'yes')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '15'))
# The authenticated SMTP login is the natural From address, so it is the
# fallback whenever a relay is configured — one fewer variable to manage.
DEFAULT_FROM_EMAIL = (
    os.environ.get('DEFAULT_FROM_EMAIL')
    or EMAIL_HOST_USER
    or 'noreply@cbods.local'
)

# Password reset links expire after a day rather than Django's default three.
# The wording in password_reset_email.txt states this figure, so the two move
# together.
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24

# Screening thresholds (assumed values, adjustable here)
SCREENING_HEMOGLOBIN_MIN = 12.5
SCREENING_SYSTOLIC_MIN = 90
SCREENING_SYSTOLIC_MAX = 180
SCREENING_DIASTOLIC_MIN = 60
SCREENING_DIASTOLIC_MAX = 100

# Eligibility rules (assumed values, adjustable here)
DONOR_MIN_AGE = 18
DONOR_MAX_AGE = 60
DONOR_MIN_WEIGHT_KG = 50
DONATION_INTERVAL_DAYS = 90

# Inventory rules (assumed values, adjustable here)
BLOOD_BAG_SHELF_LIFE_DAYS = 35
EXPIRY_WARNING_DAYS = 7
LOW_STOCK_THRESHOLD = 3

# List pages (donor search, audit log, request inbox, screening list)
LIST_PAGE_SIZE = 25

# Uploaded government-ID documents
ID_DOCUMENT_MAX_BYTES = 5 * 1024 * 1024

# Fast password hashing during tests only (dev convenience, not used in runserver)
if "test" in sys.argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
